name: Copy Netflix Data from Azure Blob to GitHub

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 3 * * *'  # Every day at 3 AM UTC (optional)

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Download file from Azure Blob Storage
        run: |
          az storage blob download \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name adf-export \
            --name output/netflix.csv \
            --file data/netflix.csv

      - name: Commit and push file to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/netflix.csv
          git commit -m "Sync Netflix CSV from Azure Blob"
          git push
