name: Sync File from Azure Blob to GitHub

on:
  workflow_dispatch:     # Allows manual trigger
  schedule:
    - cron: '0 4 * * *'   # Optional: Run daily at 4 AM UTC

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Download CSV from Azure Blob
        run: |
          az storage blob download \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name adf-export \
            --name output/netflix.csv \
            --file data/netflix.csv

      - name: Commit & push to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/netflix.csv
          git commit -m "Automated: Sync netflix.csv from Azure"
          git push

