name: Sync NetflixCast from ADLS Gen2 to GitHub

on:
  workflow_dispatch:  # You can also use schedule or push

permissions:
  contents: write  # 👈 Required to allow git push from Actions

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Azure CLI
      uses: azure/setup-azurecli@v1

    - name: Download NetflixCast.csv from Azure Blob
      run: |
        az storage blob download \
          --account-name projectnetflix1 \
          --container-name bronze \
          --name NetflixCast \
          --file data/NetflixCast \
          --sas-token "${{ secrets.AZURE_SAS_TOKEN }}"

    - name: Commit and Push to GitHub
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/NetflixCast
        git commit -m "Sync NetflixCast from ADLS Gen2"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:main
