name: Sync NetflixCast from ADLS Gen2 to GitHub

on:
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Azure CLI manually
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Download NetflixCast.csv from Azure Blob
        run: |
          az storage blob download \
            --account-name projectnetflix1 \
            --container-name bronze \
            --name NetflixCountries \
            --file data/netflix_countries \
            --sas-token "${{ secrets.AZURE_SAS_TOKEN }}"

      - name: Commit and Push to GitHub
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/netflix_countries
          git commit -m "Sync NetflixCountries from ADLS Gen2"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main
